# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="event_metrics",
    version="0.1.0",
    python_requires="==3.*,>=3.5.0",
    author="simon-mo",
    author_email="xmo@berkeley.edu",
    packages=["event_metrics"],
    package_dir={"": "."},
    package_data={},
    install_requires=["numpy"],
    extras_require={
        "dev": [
            "pytest==5.*,>=5.2.0",
            "pytest-benchmark==3.*,>=3.2.2",
            "pytest-sugar==0.*,>=0.9.2",
        ]
    },
)
